### ISSUE TITLE
TypeError: Cannot read property 'slice' of null (In file ...)

### ISSUE THREAD

**Issue by show0k** [piranna/gitbook-plugin-printlinks#1]
If I have the plugin printlinks activated, I have the error in the title at the pdf generation.
Alternativement I have a "TypeError: Cannot read property 'length' of null (In file ...) error.

**Comment by piranna** [comment]
Could you be able to provide more info? Are you sure is not a GitBook bug? It's somewhat picky with this things... Can you exec it in debug mode and give me the trace?

**Comment by show0k** [comment]
If printlinks is in booj.json plugins I have the error, if I remove it the build works...
The stacktrace:
`
TypeError: Cannot read property 'slice' of null (In file 'from-simulation-to-real-robot/using-jupyter.md')
TypeError: Cannot read property 'slice' of null
    at processPage (/home/theo/Documents/code/poppy-docs/node_modules/gitbook-plugin-printlinks/index.js:59:30)
    at /home/theo/.gitbook/versions/2.6.7/lib/plugin.js:210:25
    at _fulfilled (/home/theo/.gitbook/versions/2.6.7/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/theo/.gitbook/versions/2.6.7/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/theo/.gitbook/versions/2.6.7/node_modules/q/q.js:749:13)
    at /home/theo/.gitbook/versions/2.6.7/node_modules/q/q.js:810:14
    at flush (/home/theo/.gitbook/versions/2.6.7/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)`

If it may help:

``` bash
$ gitbook versions
GitBook Versions Installed:
    * 2.6.7
$ gitbook --version
1.0.1
$ nodejs --version
v0.10.25
$ node --version
v4.0.0
```

Note that the bug was also present with the gitbook continuous integration.
[Here](https://github.com/poppy-project/poppy-docs/tree/test-pdf) is my gitbook project (a branch with the falling version) if you want to test directly.

**Comment by piranna** [comment]
Why do you have two different versions of Node.js? Seems to me you are
using the bad one...

**Comment by show0k** [comment]
> Note that the bug was also present with the gitbook continuous integration.

I think that there is no doubt that their nodejs install is correct ; it is not the problem.

**Comment by piranna** [comment]
Can you check what's the variable getting null and why? I don't have time at this moment to fix this.

**Comment by show0k** [comment]
I tested again with you last version, and now the error message is more understandable:

> ReferenceError: page is not defined (...)

But I still don't understand where it comes from.

**Comment by piranna** [comment]
Seems a problem of GitBook itself. This plugin have just been updated to be compatible with latest one, could you be able to check if it works now?
